version: '2.1'

services:
  vendor:
    build: vendor
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes: ./image:/image

  front:
    build: front
    mem_limit: 350m
    ports:
      - "80:80"

  chat:
    build: chat
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      kafka:
        condition: service_started

  qna:
    build: qna
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notice:
    build: notice
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    build: review
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  eureka:
    build: eureka
    mem_limit: 350m

  gateway:
    build: gateway
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"

  auth:
    build: auth
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    mem_limit: 350m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=kafka-chatting:1:1
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    mem_limit: 350m
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper